<a href="https://colab.research.google.com/github/adasrinivas1229/NUMPY_STACK/blob/master/numpybymlm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# SHAPE DTYPE AND NDIM attributes of an ARRAY

A simple way to create an array from data or simple Python data structures like a list is to use the array() function.

The example below creates a Python list of 3 floating point values, then creates an ndarray from the list and access the arrays’ shape and data type.

In [7]:
# create array
from numpy import array
l = [1.0, 2.0, 3.0]
a = array(l)
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

[1. 2. 3.]
(3,)
float64
1


In [8]:
# create array
from numpy import array
l = [[1.0, 2.0, 3.0]]
a = array(l)
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

[[1. 2. 3.]]
(1, 3)
float64
2


In [9]:
# create array
from numpy import array
l = [[1.0], [2.0], [3.0]]
a = array(l)
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

[[1.]
 [2.]
 [3.]]
(3, 1)
float64
2


# Functions to Create Arrays

# Empty
The empty() function will create a new array of the specified shape.

The argument to the function is an array or tuple that specifies the length of each dimension of the array to create. The values or content of the created array will be random and will need to be assigned before use.

The example below creates an empty 3×3 two-dimensional array.

In [13]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[3.8497595e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


# Zeros
The zeros() function will create a new array of the specified size with the contents filled with zero values.

The argument to the function is an array or tuple that specifies the length of each dimension of the array to create.

The example below creates a 3×5 zero two-dimensional array.

In [14]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Ones
The ones() function will create a new array of the specified size with the contents filled with one values.

The argument to the function is an array or tuple that specifies the length of each dimension of the array to create.

The example below creates a 5-element one-dimensional array.

In [15]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


# How to Index, Slice and Reshape NumPy Arrays

In [16]:
#1. From List to Arrays
# one dimensional example
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [17]:
#1. From List to Arrays
# two dimensional example
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [18]:
#2. Array Indexing
# simple indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55


In [ ]:
#2. Array Indexing
# simple indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[5])

In [20]:
#2. Array Indexing
# simple indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


In [21]:
# 2d indexing
from numpy import array
# define array
data = array([[11, 22], [33, 44], [55, 66]])
# index data
print(data[0,0])

11


In [22]:
# 2d indexing
from numpy import array
# define array
data = array([[11, 22], [33, 44], [55, 66]])
# index data
print(data[0,])

[11 22]


In [23]:
#3. Array Slicing
# simple slicing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [27]:
# simple slicing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [28]:
# simple slicing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


In [29]:
# split input and output
from numpy import array
# define array
data = array([[11, 22, 33],
		[44, 55, 66],
		[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [30]:
# split train and test
from numpy import array
# define array
data = array([[11, 22, 33],
		[44, 55, 66],
		[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [31]:
#4. Array Reshaping
# array shape
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [32]:
# array shape
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [33]:
# array shape
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [34]:
# reshape 1D array to 2D array
from numpy import array
from numpy import reshape
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


In [35]:
# reshape 2D array to 3D array
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


# A Gentle Introduction to Broadcasting with NumPy Arrays

In [37]:
#Broadcasting in NumPy
# scalar and one-dimensional
from numpy import array
a = array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [38]:
# scalar and two-dimensional
from numpy import array
A = array([[1, 2, 3], [1, 2, 3]])
print(A)
b = 2
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [39]:
# one-dimensional and two-dimensional
from numpy import array
A = array([[1, 2, 3], [1, 2, 3]])
print(A)
b = array([1, 2, 3])
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [40]:
# broadcasting error
from numpy import array
A = array([[1, 2, 3], [1, 2, 3]])
print(A.shape)
b = array([1, 2])
print(b.shape)
C = A + b
print(C)

(2, 3)
(2,)


ValueError: ignored

#Example of the axis argument

In [10]:
import numpy as np
x=np.array([[[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8]],[[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],[[18, 19, 20],[21, 22, 23],[24, 25, 26]]])
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
 x.sum(0), x.sum(1), x.sum(2)

(array([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]]), array([[ 9, 12, 15],
        [36, 39, 42],
        [63, 66, 69]]), array([[ 3, 12, 21],
        [30, 39, 48],
        [57, 66, 75]]))