<a href="https://colab.research.google.com/github/adasrinivas1229/NUMPY_STACK/blob/master/sonet_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
c = np.array([1,2,3,4,5],ndmin = 6)
print(c)

SyntaxError: positional argument follows keyword argument (<ipython-input-18-3e4aa6451ffc>, line 1)

In [ ]:
c.shape

(1, 1, 1, 1, 1, 5)

In [ ]:
d = np.dtype([('age',np.int8)])
d

dtype([('age', 'i1')])

In [ ]:
e = np.array([[1,2,3],[4,5,6]])
e.shape = (3,2)
print(e)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
f = e.reshape(2,3)
f

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
g = np.arange(12)
g.ndim
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
h = g.reshape(3,4)
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x = np.ones((5,5),dtype = np.int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
x = [1,2,3]
i = np.asarray(x)

In [ ]:
type(i)

numpy.ndarray

In [ ]:
j = np.arange(10)
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
k = j[2:7:2]
k

array([2, 4, 6])

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
a[1:2]

array([[3, 4, 5]])

In [ ]:
a[1][2]

5

* Advance Indexing

# Pandas

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.Series([5,10,15,20,25])
df

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [ ]:
df.values

array([ 5, 10, 15, 20, 25], dtype=int64)

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
labels = ['a','b','c','d','e','f']
my_list = [10,20,30]
arr = np.array([10,20,30,40,50,60])

In [ ]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data = my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
df = pd.Series(arr,labels)
df

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int32

In [ ]:
df[:4]

a    10
b    20
c    30
d    40
dtype: int32

In [ ]:
df[['a','c','e']]

a    10
c    30
e    50
dtype: int32

In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
df = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(),
                  columns = 'W X Y Z'.split())

In [ ]:
df

W         X         Y         Z
A  0.176641  0.046955 -0.649812  0.230011
B -0.813205 -1.253921  0.676913 -0.316795
C -0.111327  1.258091 -0.104598  1.671973
D -0.602448  0.208416  0.125004 -0.822847
E -0.320454 -0.064663 -0.849593 -1.033255

In [ ]:
df['X']

A    0.046955
B   -1.253921
C    1.258091
D    0.208416
E   -0.064663
Name: X, dtype: float64

In [ ]:
df[['W','Y']]

W         Y
A  0.176641 -0.649812
B -0.813205  0.676913
C -0.111327 -0.104598
D -0.602448  0.125004
E -0.320454 -0.849593

In [ ]:
df['A'] = df['W'] + df['Y']

In [ ]:
df

W         X         Y         Z         A
A  0.176641  0.046955 -0.649812  0.230011 -0.473171
B -0.813205 -1.253921  0.676913 -0.316795 -0.136293
C -0.111327  1.258091 -0.104598  1.671973 -0.215926
D -0.602448  0.208416  0.125004 -0.822847 -0.477444
E -0.320454 -0.064663 -0.849593 -1.033255 -1.170047

In [ ]:
df2 = df.drop('W',axis = 1)

In [ ]:
df

W         X         Y         Z         A
A  0.176641  0.046955 -0.649812  0.230011 -0.473171
B -0.813205 -1.253921  0.676913 -0.316795 -0.136293
C -0.111327  1.258091 -0.104598  1.671973 -0.215926
D -0.602448  0.208416  0.125004 -0.822847 -0.477444
E -0.320454 -0.064663 -0.849593 -1.033255 -1.170047

In [ ]:
df2

X         Y         Z         A
A  0.046955 -0.649812  0.230011 -0.473171
B -1.253921  0.676913 -0.316795 -0.136293
C  1.258091 -0.104598  1.671973 -0.215926
D  0.208416  0.125004 -0.822847 -0.477444
E -0.064663 -0.849593 -1.033255 -1.170047

In [ ]:
df3 = df.drop('C',axis = 0)

In [ ]:
df3

W         X         Y         Z         A
A  0.176641  0.046955 -0.649812  0.230011 -0.473171
B -0.813205 -1.253921  0.676913 -0.316795 -0.136293
D -0.602448  0.208416  0.125004 -0.822847 -0.477444
E -0.320454 -0.064663 -0.849593 -1.033255 -1.170047

In [ ]:
df

W         X         Y         Z         A
A  0.176641  0.046955 -0.649812  0.230011 -0.473171
B -0.813205 -1.253921  0.676913 -0.316795 -0.136293
C -0.111327  1.258091 -0.104598  1.671973 -0.215926
D -0.602448  0.208416  0.125004 -0.822847 -0.477444
E -0.320454 -0.064663 -0.849593 -1.033255 -1.170047

In [ ]:
df.loc["D"]

W   -0.602448
X    0.208416
Y    0.125004
Z   -0.822847
A   -0.477444
Name: D, dtype: float64

In [ ]:
df.iloc[3]

W   -0.602448
X    0.208416
Y    0.125004
Z   -0.822847
A   -0.477444
Name: D, dtype: float64

In [ ]:
data = pd.read_csv('D:\\DATA SCIENCE\\Data Sets\\File_Reading_Files\\Sample.csv')

In [ ]:
data.shape

(15, 11)

In [ ]:
data.head(11)

Row ID       Ship Mode Customer ID     Customer Name  \
0    38198        Same Day    HR-14830       Harold Ryan   
1    29047     First Class    SG-20470      Sheri Gordon   
2    19559    Second Class    EM-14065         Erin Mull   
3    23880     First Class    SV-20815        Stuart Van   
4    17765    Second Class    SB-20290      Sean Braxton   
5    36859    Second Class    JE-15610           Jim Epp   
6    39211  Standard Class    SR-20740     Steven Roelle   
7    33283     First Class    CB-12415  Christy Brittain   
8    26932  Standard Class    GB-14530       George Bell   
9    26037     First Class    CT-11995      Carol Triggs   
10   47029        Same Day    SG-10605  Speros Goranitis   

                                         Product Name     Sales  Quantity  \
0                Hewlett Packard LaserJet 3310 Copier  2399.960         5   
1                         Hewlett Wireless Fax, Color  1526.520         4   
2                         Hewlett Wireless Fax, Laser  1900.950         5   
3                     Hewlett Fax Machine, High-Speed  1590.600         5   
4                         Hewlett Wireless Fax, Color  2671.410         7   
5                Hewlett Packard LaserJet 3310 Copier  2999.950         5   
6   Hewlett-Packard Desktjet 6988DT Refurbished Pr...  3404.500         5   
7                Hewlett Packard LaserJet 3310 Copier  1439.976         4   
8                         Hewlett Wireless Fax, Laser  4448.223        13   
9                       Hewlett Wireless Fax, Digital  3038.640         8   
10                      Hewlett Fax and Copier, Color  1554.480         8   

    Discount     Profit  Shipping Cost Order Priority  
0        0.2   839.9860         630.05           High  
1        0.0   732.7200         625.77       Critical  
2        0.0   589.2000         506.89           High  
3        0.0   572.5500         493.20       Critical  
4        0.0   534.2400         483.04           High  
5        0.0  1439.9760         439.69           High  
6        0.0  1668.2050         419.06           High  
7        0.4   191.9968         408.79       Critical  
8        0.1   444.4830         386.38         Medium  
9        0.0  1245.8400         371.51           High  
10       0.0   341.7600         366.58           High

In [ ]:
data.tail()

Row ID     Ship Mode Customer ID     Customer Name  \
10   47029      Same Day    SG-10605  Speros Goranitis   
11   32050   First Class    YC-21895    Yoseph Carroll   
12    4027  Second Class    FM-14215     Filia McAdams   
13   25179      Same Day    AM-10705    Anne McFarland   
14   24610  Second Class    BP-11290        Beth Paige   

                                         Product Name      Sales  Quantity  \
10                      Hewlett Fax and Copier, Color  1554.4800         8   
11  Hewlett Packard 610 Color Digital Copier / Pri...  1199.9760         3   
12                    Hewlett Fax Machine, High-Speed  1058.2792         5   
13                        Hewlett Copy Machine, Color  1479.3138         6   
14                Hewlett Personal Copier, High-Speed  1282.2300         9   

    Discount    Profit  Shipping Cost Order Priority  
10     0.000  341.7600         366.58           High  
11     0.200  374.9925         363.78           High  
12     0.002   -2.1208         354.42       Critical  
13     0.070  -63.6462         350.31           High  
14     0.000   12.6900         349.88       Critical

In [ ]:
import json
pd.read_json("")

In [ ]:
pd.read_excel("xlsx")

In [ ]:
import xml.etree.ElementTree as et
xtree = et.parse('')
xroot = xtree.getroot()